//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernRonin.PraeterArtem.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernRonin.PraeterArtem.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Root path=&quot;/&quot; fullPath=&quot;/&quot;&gt;
        ///  &lt;Alpha bravo=&quot;1&quot;&gt;&lt;Charlie /&gt;&lt;/Alpha&gt;
        ///  &lt;Delta&gt;&lt;Echo /&gt;&lt;/Delta&gt;
        ///  &lt;Path path=&quot;Empty&quot; fullPath=&quot;Empty&quot;&gt;
        ///  &lt;/Path&gt;
        ///  &lt;Path path=&quot;Sub&quot; fullPath=&quot;Sub&quot;&gt;
        ///    &lt;Foxtrott&gt;&lt;Golf /&gt;&lt;/Foxtrott&gt;
        ///    &lt;Path path=&quot;Deep&quot; fullPath=&quot;Sub/Deep&quot;&gt;
        ///      &lt;Hotel&gt;&lt;India /&gt;&lt;/Hotel&gt;
        ///    &lt;/Path&gt;
        ///  &lt;/Path&gt;
        ///&lt;/Root&gt;.
        /// </summary>
        internal static string Regression1Left {
            get {
                return ResourceManager.GetString("Regression1Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Root path=&quot;/&quot; fullPath=&quot;/&quot;&gt;
        ///  &lt;Alpha bravo=&quot;1&quot;&gt;
        ///    &lt;Charlie /&gt;
        ///  &lt;/Alpha&gt;
        ///  &lt;Delta&gt;
        ///    &lt;Echo /&gt;
        ///  &lt;/Delta&gt;
        ///  &lt;Path path=&quot;Empty&quot; fullPath=&quot;Empty&quot; /&gt;
        ///  &lt;Path path=&quot;Sub&quot; fullPath=&quot;Sub&quot;&gt;
        ///    &lt;Foxtrott&gt;
        ///      &lt;Golf /&gt;
        ///    &lt;/Foxtrott&gt;
        ///    &lt;Path path=&quot;Deep&quot; fullPath=&quot;Deep&quot;&gt;
        ///      &lt;Hotel&gt;
        ///        &lt;India /&gt;
        ///      &lt;/Hotel&gt;
        ///    &lt;/Path&gt;
        ///  &lt;/Path&gt;
        ///&lt;/Root&gt;.
        /// </summary>
        internal static string Regression1Right {
            get {
                return ResourceManager.GetString("Regression1Right", resourceCulture);
            }
        }
    }
}
